<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl()?>/css/bootstrap.css">
<!-- Custom CSS -->
<link href="<?=$this->baseUrl()?>/css/sb-admin.css" rel="stylesheet">
<!-- Morris Charts CSS -->
<link href="<?=$this->baseUrl()?>/css/morris.css" rel="stylesheet">
<!-- Custom Fonts -->
<link href="<?=$this->baseUrl()?>/css/font-awesome.min.css" rel="stylesheet" type="text/css">

<h1 class="page-header">Categories</h1>
<div class="col-sm-offset-1 ">
    <?= $this->form; ?>
</div>
<br><hr><br>
<div class="col-sm-offset-1">
	<table class=" table table-bordered table-hover">
	<tr>
		<th>Categories</th>
		<th colspan="2">Actions</th>
	</tr>
	<?php
		foreach ($this->categories as $category) 
		{
	?>
			<tr>
				<td><?=$category['name']?></td>
				<td class="success"><a href="<?=$this->baseUrl()?>/categories/edit/id/<?=$category['id']?>">UPDATE</a></td>
				<td class="danger"><a href="<?=$this->baseUrl()?>/categories/delete/id/<?=$category['id']?>">DELETE</a></td>
			</tr>
	<?php   				
		}
	?>
	</table>
</div>

<!-- jQuery -->
<script src="<?=$this->baseUrl()?>/js/jquery.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="<?=$this->baseUrl()?>/js/bootstrap.min.js"></script>
<!-- Morris Charts JavaScript -->
<script src="<?=$this->baseUrl()?>/js/raphael.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/morris.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/morris-data.js"></script>
	