<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl()?>/css/bootstrap.css">
<!-- Custom CSS -->
<link href="<?=$this->baseUrl()?>/css/sb-admin.css" rel="stylesheet">
<!-- Morris Charts CSS -->
<link href="<?=$this->baseUrl()?>/css/morris.css" rel="stylesheet">
<!-- Custom Fonts -->
<link href="<?=$this->baseUrl()?>/css/font-awesome.min.css" rel="stylesheet" type="text/css">

<h1 class="page-header">Category <small> Edit</small></h1>
<div class="col-sm-offset-1 ">
	<?php
		echo $this->form;
	?>
</div>
<br><hr><br>

<!-- jQuery -->
<script src="<?=$this->baseUrl()?>/js/jquery.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="<?=$this->baseUrl()?>/js/bootstrap.min.js"></script>
<!-- Morris Charts JavaScript -->
<script src="<?=$this->baseUrl()?>/js/raphael.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/morris.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/morris-data.js"></script>