
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/bootstrap.css">
  <link rel="stylesheet" href="<?=$this->baseUrl()?>/css/font-awesome.min.css">
  <link rel="stylesheet" href="<?=$this->baseUrl()?>/css/templatemo_style.css">
  <link rel="stylesheet" href="<?=$this->baseUrl()?>/css/templatemo_misc.css">
  <link rel="stylesheet" href="<?=$this->baseUrl()?>/css/flexslider.css">
  <link rel="stylesheet" href="<?=$this->baseUrl()?>/css/testimonails-slider.css">
  <script src="<?=$this->baseUrl()?>/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>
  <style>
      /* .tales {
          width: 70%;
          height :500px;
          text-align:center;
          margin:auto;
        }
        .carousel-inner{
          width:600px;
          max-height: 400px ;
        }
 */        .carousel slide{
          width:600px;
        }
        .carousel-caption{
          color:red;
        }

  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 80%;
      margin: auto;
  }
  #myCarousel{
   width:100%;
   max-height:600px;
   margin: auto;
   margin-top: 40px;
  }
  
  

  </style>
  <script>
      $(function()
            {
                $( '.carousel-inner .item:first' ).addClass( 'active' );    
              
            }
      );
  </script>


<div id="welcome">
    <div class="container" id="slider" >

    <div class="heading-section">
        <h2>Last Free Courses</h2>
        <img src="images/under-heading.png" alt="" >
    </div>

      <!-- <h2> Home Page </h2> -->


  <div id="myCarousel" class="carousel slide" data-ride="carousel" >
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
      
    </ol>

   

      <?php 
       echo "<div class='carousel-inner' role='listbox'>";
 
      //   echo "<div class='item active'>";          
      //   echo "<img src='".$this->baseUrl().'/images/'.$this->courses[0]['image']."' class= 'tales'>";
      //   echo "<div class='carousel-caption'>";
      //   // echo "<h3> ".$cor['name']."</h3>";
      //   echo "<h3><a href='".$this->baseUrl()."/courses/singlecourse/id/".$this->courses[0]['id']."'> ".$this->courses[0]['name']."</a></h3>";
      //   // echo "<p>".$cor['description']."</p>";
      //   echo " </div>";
      //   echo " </div>";
        
      
      foreach ($this->courses as $cor) 
      {
      // $val = '4.png';
        
        
                echo "<div class='item '>";          
                echo "<img src='".$this->baseUrl().'/upload/courses/'.$cor['image']."' class= 'tales'>";
                echo "<div class='carousel-caption'>";
                // echo "<h3> ".$cor['name']."</h3>";
                echo "<h3><a href='".$this->baseUrl()."/courses/singlecourse/id/".$cor['id']."'> ".$cor['name']."</a></h3>";
                // echo "<p>".$cor['description']."</p>";
                echo " </div>";
                echo " </div>";
        
      
    } 
echo " </div>";
    ?>
    

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

    </div>
</div>
  
<?php 
  
  // foreach ($this->courses as $cor) 
  // {
  //     echo $cor['image'];    
  //     echo $cor['description'];
  // }

?>


<div id="services">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="heading-section">
                                <h2>Free Online Courses </h2>
                                <img src="images/under-heading.png" alt="" >
                            </div>
                        </div>
                    </div>
                    <?php
                      foreach ($this->cats as  $cat) {
                        
                      
                      echo "<div class='row'>";
                      echo "<div class='col-md-3 col-sm-6'>";
                      echo "<div class='service-item'>";       
                      echo "<div class='icon'>";
                      echo "<i class='fa fa-pencil'></i>";
                      echo " </div>";
                      // echo "<h4>".$cat['name']."</h4>";
                      echo "<h3><a href='".$this->baseUrl()."/courses/singlecategory/catId/".$cat['id']."'> ".$cat['name']."</a></h3>";
                      echo"<p>".$cat['description']."</p>";

                        echo "</div>";      
                        echo" </div>";
                      }
                      
                       ?>
                          
                    </div>
                </div>
            </div>

            <footer>
                <div class="container">
                    <div class="top-footer">
                        <div class="row">
                            <div class="col-md-9">
                                <div class="subscribe-form">
                                    <span>Get in touch with us</span>
                                    <form method="get" class="subscribeForm">
                                        <input id="subscribe" type="text" />
                                        <input type="submit" id="submitButton" />
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="social-bottom">
                                    <span>Follow us:</span>
                                    <ul>
                                        <li><a href="#" class="fa fa-facebook"></a></li>
                                        <li><a href="#" class="fa fa-twitter"></a></li>
                                        <li><a href="#" class="fa fa-rss"></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="main-footer">
                        <div class="row">
                            <div class="col-md-3">
                              
                            </div>
                            <div class="col-md-3">
                                
                            </div>
                            <div class="col-md-3">
                                
                            </div>
                            <div class="col-md-3">
                                <div class="more-info">
                                    <h4 class="footer-title">More info</h4>
                                    <p>Sed dignissim, diam id molestie faucibus, purus nisl pretium quam, in pulvinar velit massa id elit.</p>
                                    <ul>
                                        <li><i class="fa fa-phone"></i>010-020-0340</li>
                                        <li><i class="fa fa-globe"></i>123 Dagon Studio, Yakin Street, Digital Estate</li>
                                        <li><i class="fa fa-envelope"></i><a href="#">info@company.com</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bottom-footer">
                        <p>
                          <span>Copyright © 2084 <a href="#">Your Company Name</a> 
                            | Design: <a rel="nofollow" href="http://www.templatemo.com" target="_parent"><span class="blue">template</span><span class="green">mo</span></a></span>
                        </p>
                    </div>
                    
                </div>
            </footer>





   



<script src="<?=$this->baseUrl()?>/js/jquery-1.11.0.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/jquery.gmap3.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/plugins.js"></script>
<script src="<?=$this->baseUrl()?>/js/main.js"></script> <!-- images motion