<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl()?>/css/bootstrap.css">


<!-- Custom CSS -->
    <link href="<?=$this->baseUrl()?>/css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href=


<br /><br />
<div id="view-content">
	<p>View script for controller <b>Requests</b> and script/action name <b>add</b></p>
	<h3> Request </h3>

</div>
<div class="col-md-4">
<?php 
	echo $this->form ;
	?>
</div>



<script src="<?=$this->baseUrl()?>/js/jquery.js"></script>
    <script src="<?=$this->baseUrl()?>/js/raphael.min.js"></script>
    <script src="<?=$this->baseUrl()?>/js/morris.min.js"></script>
    <script src="<?=$this->baseUrl()?>/js/morris-data.js"></script>