<br /><br />
<div class="container">
	<!-- <p>View script for controller <b>Requests</b> and script/action name <b>home</b></p> -->

	<nav class="navbar navbar-inverse">
		<ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Link</a></li>
  	</nav>

	<h2> Home Page </h2>


	  <div id="myCarousel" class="carousel slide" data-ride="carousel" >
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->

<!--     <div class="carousel-inner" role="listbox">

      <div class="item active">

        <img src="<?php echo $this->baseUrl() . '/images/1.png' ?>" alt="Chania" >
        <div class="carousel-caption">
          <h3>Travel</h3>
         
        </div>
      </div>

      <div class="item">
        <img src="<?php echo $this->baseUrl() . '/images/4.png' ?>" alt="Chania" >
        <div class="carousel-caption">
          <h3>SleepinG</h3>
          
        </div>
      </div>
    </div>
 -->
     

  		<?php 

  		$array = ['1.png','4.png'];
  		foreach($array as $val)
  		{

	  		echo "<div class='carousel-inner' role='listbox'>";
			echo "<div class='item'>";		      
			echo "<img src='".$this->baseUrl().'/images/'.$val."'>";
			echo "<div class='carousel-caption'>";
			echo "<h3>title</h3>";
			      //   <p>{{ $val['description']}}</p>
			echo " </div>";
			echo " </div>";
		 	echo "</div>";
		  
		} 
		?>
    

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


</div>


