
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl()?>/css/bootstrap.css">


<!-- Custom CSS -->
    <link href="<?=$this->baseUrl()?>/css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="<?=$this->baseUrl()?>/css/morris.css" rel="stylesheet">


<br /><br />
<div id="view-content">
	<!-- <p>View script for controller <b>Requests</b> and script/action name <b>list</b></p> -->
	<h2> <b> List all unread requests :  <b> </h2>
</div>

<?php

	echo "<a style='margin-left:400px'href='".$this->baseUrl()."/requests/index'> list all requests </a><br>";
	foreach ($this->requests as $req)
	{
		


		
	// echo "<label> <b> ID: </b> </label>".$req['id'].'<br />';
	echo "<label style='color:orange'> <b> RequestContent : </b> </label>".$req['content'].'<br />';



	// echo "<label> <b> User: </b> </label>".$req['user_id'].'<br />';
	echo "<label> <b> From : </b> </label>".$req['name'].'<br />';
	
	
	echo "<hr>";

	
		
	}
	echo "<h3> <b>Add new material and course  </b></h3>";
	echo "<a href='".$this->baseUrl()."/material/upload/'> Newmaterial </a>";
	echo "<a style='margin-left:100px'href='".$this->baseUrl()."/courses/crud/'> Newcourse </a>";

	// echo $this->material;

	

?>


<script src="<?=$this->baseUrl()?>/js/jquery.js"></script>
    <script src="<?=$this->baseUrl()?>/js/raphael.min.js"></script>
    <script src="<?=$this->baseUrl()?>/js/morris.min.js"></script>
    <script src="<?=$this->baseUrl()?>/js/morris-data.js"></script>