<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl()?>/css/bootstrap.css">


<!-- Custom CSS -->
    <link href="<?=$this->baseUrl()?>/css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="<?=$this->baseUrl()?>/css/morris.css" rel="stylesheet"> 	
       		
   		<h1 class="page-header">
              Materials
      </h1>
   		<div class="col-sm-offset-1 ">
			<?php
				echo $this->form;
			?>
		</div>
    <br><hr><br>
    <!-- <div class="col-sm-offset-1"> -->
    
    <!-- </div> -->
		<script src="<?=$this->baseUrl()?>/js/jquery.js"></script>
    <script src="<?=$this->baseUrl()?>/js/raphael.min.js"></script>
    <script src="<?=$this->baseUrl()?>/js/morris.min.js"></script>
    <script src="<?=$this->baseUrl()?>/js/morris-data.js"></script>