<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/bootstrap.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/font-awesome.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/templatemo_style.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/templatemo_misc.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/flexslider.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/testimonails-slider.css">
<script src="<?=$this->baseUrl()?>/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>

<div style="text-align:center"> 
  <button onclick="playPause()">Play/Pause</button> 
  <button onclick="makeBig()">Big</button>
  <button onclick="makeSmall()">Small</button>
  <button onclick="makeNormal()">Normal</button>
  <br><br>
  <video id="video1" width="420" controls="" autoplay="" src="/SLMS_zend/public/upload/material/php.mp4">
    
  </video>

</div> 
 

<script> 
var myVideo = document.getElementById("video1"); 

function playPause() { 
    if (myVideo.paused) 
        myVideo.play(); 
    else 
        myVideo.pause(); 
} 

function makeBig() { 
    myVideo.width = 560; 
} 

function makeSmall() { 
    myVideo.width = 320; 
} 

function makeNormal() { 
    myVideo.width = 420; 
} 
</script>
<script src="<?=$this->baseUrl()?>/js/jquery-1.11.0.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/jquery.gmap3.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/plugins.js"></script>
<script src="<?=$this->baseUrl()?>/js/main.js"></script>