<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>
<?php
    $data = Zend_Auth::getInstance()->getStorage()->read();
    $is_admin = $data->type;
    $name=$data->name;
?>

<!-- <?php
$this->headLink()->prependStylesheet("http://localhost/Zend/SLMS_project/public/css/bootstrap.css");
$this->headLink()->prependStylesheet("http://localhost/Zend/SLMS_project/public/css/font-awesome.css");//client
$this->headLink()->prependStylesheet("http://localhost/Zend/SLMS_project/public/css/templatemo_style.css");//client
$this->headLink()->prependStylesheet("http://localhost/Zend/SLMS_project/public/css/templatemo_misc.css");//client
$this->headLink()->prependStylesheet("http://localhost/Zend/SLMS_project/public/css/flexslider.css");//client
$this->headLink()->prependStylesheet("http://localhost/Zend/SLMS_project/public/css/testimonails-slider.css");//client
$this->headLink()->prependStylesheet("http://localhost/Zend/SLMS_project/public/css/font-awesome.min.css");//client

?> -->



</head>
<body>
<!-- ***************************HEADER****************************** -->
<header>
    <div id="top-header">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="home-account">
                        <a href=<?=$this->baseUrl()?> >Home</a>
                    </div>
                </div>
                <div class="col-md-10">
                    <div class="cart-info">
                        welcome <a href="#"><?=$name?></a>
                        <?php
                       echo "<a class='col-sm-offset-1' href='".$this->baseUrl()."/users/logout/'>Logout</a>";
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="main-header">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="logo">
                        <a href="#"><h1>SLMS</h1></a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="main-menu">
                        <ul>
                            <?php
                            if($is_admin == '1')
                            {
                                ?>
                                <li><a href="<?=$this->baseUrl()?>/categories/crud" >Dash Board</a></li>
                                <?php
                            }
                            ?>
                           <!--  <li><a href="about-us.html">About</a></li>
                            <li><a href="products.html">Products</a></li>
                            <li><a href="contact-us.html">Contact</a></li> -->
                        </ul>
                    </div>
                </div>
                <!-- <div class="col-md-3">
                    <div class="search-box">  
                        <form name="search_form" method="get" class="search_form">
                            <input id="search" type="text" />
                            <input type="submit" id="search-button" />
                        </form>
                    </div>
                </div> -->
            </div>
        </div>
    </div>
</header>
<!-- **************************END HEADER***************************** -->

<?php echo $this->layout()->content; ?>


<!-- <?php
$this->headScript()->prependFile('http://localhost/Zend/SLMS_project/public/js/jquery.js');

$this->headScript()->prependFile('http://localhost/Zend/SLMS_project/public/js/bootstrap.js');

$this->headScript()->prependFile('http://localhost/Zend/SLMS_project/public/js/modernizr-2.6.1-respond-1.1.0.min.js');//client

$this->headScript()->prependFile('http://localhost/Zend/SLMS_project/public/js/jquery-1.11.0.min.js');//client

$this->headScript()->prependFile('http://localhost/Zend/SLMS_project/public/js/jquery.gmap3.min.js');//client

$this->headScript()->prependFile('http://localhost/Zend/SLMS_project/public/js/plugins.js');//client

$this->headScript()->prependFile('http://localhost/Zend/SLMS_project/public/js/main.js');//client
?> -->
</body>
</html>